# Generated by Django 3.2 on 2023-06-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230525_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='ciclos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ciclo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='dashboard.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='ciclo',
            unique_together={('carrera', 'numero')},
        ),
    ]
