# Generated by Django 3.2 on 2023-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_curso_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(to='dashboard.Alumno'),
        ),
    ]
