# Generated by Django 3.2 on 2023-06-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_curso_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cursos',
        ),
        migrations.AlterField(
            model_name='aula',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='dashboard.Curso'),
        ),
    ]
