# Generated by Django 3.2 on 2023-06-01 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230531_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cuenta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cuenta'),
        ),
    ]
