# Generated by Django 3.2 on 2023-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alumno_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carreras/'),
        ),
    ]
