# Generated by Django 3.2 on 2023-06-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20230602_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='deber_1',
            new_name='Laboratorio_01',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_10',
            new_name='Laboratorio_02',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_11',
            new_name='Laboratorio_03',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_12',
            new_name='Laboratorio_04',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_13',
            new_name='Laboratorio_05',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_14',
            new_name='Laboratorio_06',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_15',
            new_name='Laboratorio_07',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_16',
            new_name='Laboratorio_08',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_2',
            new_name='Laboratorio_09',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_3',
            new_name='Laboratorio_10',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_4',
            new_name='Laboratorio_11',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_5',
            new_name='Laboratorio_12',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_6',
            new_name='Laboratorio_13',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_7',
            new_name='Laboratorio_14',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_8',
            new_name='Laboratorio_15',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='deber_9',
            new_name='Laboratorio_16',
        ),
    ]
