# Generated by Django 3.2 on 2023-06-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20230602_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
