# Generated by Django 3.2 on 2023-06-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.alumno')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.laboratorio')),
            ],
        ),
    ]
