# Generated by Django 3.2 on 2023-06-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20230603_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='cursos',
        ),
    ]
