# Generated by Django 3.2 on 2023-06-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20230603_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('A', 'Asistió'), ('T', 'Tardanza'), ('F', 'Faltante')], max_length=1),
        ),
    ]
